# Generated by Django 4.2.16 on 2026-06-12 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecriture', models.DateField()),
                ('numero_piece', models.CharField(blank=True, default='', max_length=60)),
                ('fournisseur_client', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('import', 'Import'), ('scanner', 'Scanner')], default='manuel', max_length=20)),
                ('confiance_ia', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_ecriture', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=50, unique=True)),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateField()),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('ville', models.CharField(blank=True, default='', max_length=120)),
                ('code_postal', models.CharField(blank=True, default='', max_length=20)),
                ('exercice_comptable', models.CharField(max_length=20)),
                ('banque', models.CharField(blank=True, default='', max_length=120)),
                ('numero_compte', models.CharField(blank=True, default='', max_length=60)),
                ('rib', models.CharField(blank=True, default='', max_length=60)),
                ('regime_fiscale', models.CharField(blank=True, default='', max_length=120)),
                ('activite', models.CharField(blank=True, default='', max_length=255)),
                ('matiere_premiere', models.CharField(blank=True, default='', max_length=255)),
                ('marchandise', models.CharField(blank=True, default='', max_length=255)),
                ('matieres_consommables', models.CharField(blank=True, default='', max_length=255)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='core.entreprise')),
            ],
            options={
                'ordering': ['-annee'],
                'unique_together': {('entreprise', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20)),
                ('libelle', models.CharField(blank=True, default='', max_length=255)),
                ('montant_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.ecriture')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_journal', models.CharField(choices=[('achat', 'Achats'), ('vente', 'Ventes'), ('banque', 'Banque'), ('caisse', 'Caisse'), ('od', 'Opérations diverses')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.exerciceannee')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.entreprise')),
            ],
            options={
                'ordering': ['type_journal'],
                'unique_together': {('entreprise', 'annee', 'type_journal')},
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, default='', max_length=60)),
                ('date_facture', models.DateField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva_pourcentage', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_cours', max_length=20)),
                ('confiance_ia', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.ecriture')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.entreprise')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ecriture',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='core.journal'),
        ),
        migrations.CreateModel(
            name='ClientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='core.entreprise')),
            ],
            options={
                'unique_together': {('client', 'entreprise')},
            },
        ),
    ]
