# Generated by Django 4.2.16 on 2026-06-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['type_journal', 'nom']},
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='activite2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='banque2',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='numero_compte2',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='rib2',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='journal',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='journal',
            name='type_journal',
            field=models.CharField(choices=[('achat', 'Achats'), ('vente', 'Ventes'), ('banque', 'Banque'), ('caisse', 'Caisse'), ('od', 'Opérations diverses'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('entreprise', 'annee', 'type_journal', 'nom')},
        ),
    ]
