# Generated by Django 4.2.16 on 2026-06-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ecriture_mode_paiement_facture_mode_paiement'),
        ('core', '0003_fournisseur_message_clientcomptable'),
    ]

    operations = [
    ]
