# Generated by Django 4.2.16 on 2026-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260626_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fournisseur_client',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente')], default='achat', max_length=20),
        ),
    ]
