# Generated by Django 4.2.16 on 2026-08-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_facture_fournisseur_client_facture_type_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('banque', 'Relevé bancaire')], default='achat', max_length=20),
        ),
    ]
