# Generated by Django 4.2.16 on 2026-08-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_facture_type_banque'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriture',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
