# Generated by Django 4.2.16 on 2026-08-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ecriture_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente')], default='achat', max_length=20),
        ),
        migrations.CreateModel(
            name='SCFAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('classe', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scf_accounts', to='core.entreprise')),
            ],
            options={
                'ordering': ['classe', 'numero_compte'],
                'unique_together': {('entreprise', 'numero_compte')},
            },
        ),
    ]
