# Generated by Django 4.2.16 on 2026-09-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_renumber_bank_scf_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='nif',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(condition=models.Q(('nif', ''), _negated=True), fields=('accountant', 'nif'), name='unique_nif_per_accountant'),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(condition=models.Q(('nis', ''), _negated=True), fields=('accountant', 'nis'), name='unique_nis_per_accountant'),
        ),
    ]
