# Generated by Django 4.2.16 on 2026-09-01 20:18

from django.db import migrations


class Migration(migrations.Migration):
    """Originally added a unique constraint on (accountant, nom).

    Migration 0013, added in the same commit, drops that constraint again and
    `Entreprise.Meta` never carried it, so the pair is a no-op overall. Creating
    the index still failed on any database that already holds two organisations
    with the same name under one accountant, which blocked every later
    migration, so both steps are now empty.
    """

    dependencies = [
        ('core', '0011_per_accountant_nif_nis_uniqueness'),
    ]

    operations = []
