# Generated by Django 4.2.16 on 2026-09-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_per_accountant_nif_nis_uniqueness'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(fields=('accountant', 'nom'), name='unique_nom_per_accountant'),
        ),
    ]
