# Generated by Django 4.2.16 on 2026-09-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_per_accountant_nom_uniqueness'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entreprise',
            name='unique_nom_per_accountant',
        ),
    ]
